server:
  port: 8083

spring:
  application:
    name: notification-service

  datasource:
    url: jdbc:postgresql://postgres:5432/orderflow
    username: postgres
    password: postgres

  flyway:
    default-schema: notifications
    schemas: notifications

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: notifications
    show-sql: true

  kafka:
    bootstrap-servers: kafka:9092

management:
  endpoints:
    web:
      exposure:
        include: "*"
