server:
  port: 8082

spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:postgresql://postgres:5432/orderflow
    username: postgres
    password: postgres

  flyway:
    default-schema: payments
    schemas: payments

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: payments
    show-sql: true

  kafka:
    bootstrap-servers: kafka:9092

management:
  endpoints:
    web:
      exposure:
        include: "*"
